import glob
import pandas as pd

configfile: "../../config/config.yaml"

pre_path = config["preprocessing_path"]
out_path = config["out_path"]["single"]

metadata = pd.read_csv(config["metadata"], sep = "\t", index_col = 0)
samples = metadata.index.tolist()
groups = metadata["group"].unique().tolist()

include: "rules/downloads.smk"
include: "rules/bwa.smk"
include: "rules/preprocessing.smk"
include: "rules/gatk_single_calling.smk"
include: "rules/validate.smk"

rule all:
	input:
		expand(rules.gatk_haplotypecaller.output.vcf, sample = samples),
		expand(rules.funcotator.output.vcf, sample = samples),
		expand(rules.concordance_NA12878.output, sample = ["NIST7035", "NIST7086"])

def get_samples_given_group(group):
	return metadata.loc[metadata["group"] == group, :].index.tolist()

